web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis
    - redis2
  volumes:
    - ./web/code/:/code/
  #command: /bin/bash
  command: bash -c "supervisord -c /etc/supervisor/supervisord.conf; python manage.py runserver 0.0.0.0:8000"
  #command: bash -c "/etc/init.d/celeryd start ; python manage.py runserver 0.0.0.0:8000"
  #command: /usr/local/bin/gunicorn -w 2 -b :8000 perfproject.wsgi
     
redis:
  build: ./redis

redis2:
  build: ./redis
  
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./web/app/static:/www/static
  volumes_from:
    - web
  links:
    - web:web

#data:
#  restart: always
#  image: postgres:latest
#  volumes:
#    - /var/lib/postgresql
#  ports:
#    - "5433:5432"
#  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - ./db/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"
